version: '3.8'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=127.0.0.1
      - REDIS_PORT=6379
    volumes:
      - .:/usr/src/app
  redis:
    image: redis:7
    ports:
      - "6379:6379"